const EVENTS={
    CREATE_ROOM:"CREATE_ROOM",
    VIEW_ROOM:"VIEW_ROOM",
    SHOW_ROOM:"SHOW_ROOM",
    NO_ROOM:"NO_ROOM",
    JOIN_ROOM:"JOIN_ROOM",
    HAS_GAME:"HAS_GAME",
    NOT_MEMBER:"NOT_MEMBER",

    SEE_OTHER_PLAYERS:"SEE_OTHER_PLAYERS",
    SEE_PLAYER:"SEE_PLAYERS",

    SET_GAME:"START_GAME",
    STARTING:"STARTING",
    BEGIN:"BEGIN",
    QUESTIONS_ERROR:"QUESTIONS_ERROR",

    UPDATE_SCORE:"UPDATE_SCORE",
    GET_FINAL_SCORES:"GET_FINAL_SCORES",
    RECEIVE_FINAL_SCORES:"RECEIVE_FINALSCORES",

    SUBMIT_TIMER:"SUBMIT_TIMER",
    GET_QUESTION:"GET_QUESTION",
    RECEIVE_QUESTION:"RECEIVE_QUESTION",

    SUBMIT_ANSWER:"SUBMIT_ANSWER",
    WAITING:"WAITING",

    CHECKING:"CHECKING",
    ANSWER_CHECK_ERROR:"ANSWER_CHECK_ERROR",
    LAST_QUESTION:"LAST_QUESTION",
    RECEIVE_VERDICT:"RECEIVE_VERDICT",

    SET_TIME_OFFSET:"SET_TIMER_OFFSET"

} as const
export default EVENTS
